### ISSUE TITLE
localStorage might never be cleared

### ISSUE THREAD

**Issue by kurtextrem** [iamakulov/googlefonts-font-display-helper#10]
https://developers.google.com/web/fundamentals/performance/resource-prioritization
"Caution: If you’re using a CDN, such as Google Fonts, be sure that the font files you’re preloading match the ones in the CSS, which can be tricky due to unicode ranges, weights, and font variants. Fonts can also be regularly updated, and if you’re preloading an old version while using the CSS for a newer one, you may end up downloading two versions of the same font and wasting your users’ bandwidth. Consider using <link rel="preconnect"> instead for easier maintenance."
---> localStorage might never get cleared - this means that font urls might not exist anymore (or might be outdated).

So either a switch to sessionStorage is needed, or some kind of trial-and-erorr check, a checksum (e.g. always fetch the google sheet and re-apply if checksum changed), ...

**Comment by iamakulov** [comment]
Hmm. That’s a great point.

One reason I’m using `localStorage` is that when a font is cached, we need to insert the stylesheet synchronously – or, otherwise, we’ll be causing a FOUT each time a page is loaded.

Probably it’s a good idea to still fetch and insert the stylesheet – even if we already inserted a cached one from `localStorage`.

**Comment by kurtextrem** [comment]
sessionStorage is sync too (and clears itself after browser restarts). So it's either: short term caching (= session) and not a lot of logic, or localStorage and a lot of logic to check for updates.

**Comment by iamakulov** [comment]
Yeah, but the snippet needs to have long-term synchronous caching to avoid a FOUT.

If we save the stylesheet in `sessionStorage`, and the user relaunches the browser, the next time a page is loaded, they will have to re-download the stylesheet asynchronously. Even if the stylesheet is cached in the browser cache, `fetch()` would still resolve – and we would insert the `style` tag – after the page got rendered, and the user will experience a short FOUT.

Or am I thinking wrong?

**Comment by kurtextrem** [comment]
Yes, indeed that would happen.
But the worse thing would be to insert a font url that ends in a 404.

So a logic could be to save a "check" state in sessionStorage:
if localStorage has the key
	if sessionStorage doesn't have the check key
		insert from localStorage
		check using fetch if there are new links
		if yes: insert new links, replace old
		if no: do nothing
		set check key

**Comment by iamakulov** [comment]
I’m actually thinking about the same logic, but with `localStorage` only:

```
// Main flow
if localStorage has the stylesheet cached:
  insert from localStorage

doFetch
save the fetched stylesheet into localStorage

// doFetch()
def doFetch:
  fetch the stylesheet
  if a style tag was already inserted from localStorage:
    update the style tag content from the fetched result
  else:
    insert a new style tag from the fetched result
```

Not sure why might we need both `localStorage` and `sessionStorage`?

**Comment by kurtextrem** [comment]
Because sessionStorage would prevent fetching N times during a session. I don't really see a new for fetching on every page reload for example (even though it would be cached).

**Comment by iamakulov** [comment]
Ah, makes sense!

Fetching would still happen though – we use `<link rel="preload">` that would initiate a fetch anyway.
