### ISSUE TITLE
Generate wrong snippit with hyphen

### ISSUE THREAD

**Issue by joshuaavalon** [iamakulov/googlefonts-font-display-helper#13]
### Input
```
https://fonts.googleapis.com/css?family=Noto+Sans+TC:300,400,700&amp;subset=chinese-traditional,japanese
```

### Result
```
<!-- Code snippet to speed up Google Fonts rendering: googlefonts.3perf.com -->
<link rel="dns-prefetch" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous">
<link rel="preload" href="https://fonts.googleapis.com/css?family=Noto+Sans+TC:300,400,700&amp;subset=chinese" as="fetch" crossorigin="anonymous">
<script type="text/javascript">
!function(e,n,t){"use strict";var o="https://fonts.googleapis.com/css?family=Noto+Sans+TC:300,400,700&amp;subset=chinese",r="__3perf_googleFontsStylesheet";function c(e){(n.head||n.body).appendChild(e)}function a(){var e=n.createElement("link");e.href=o,e.rel="stylesheet",c(e)}function f(e){if(!n.getElementById(r)){var t=n.createElement("style");t.id=r,c(t)}n.getElementById(r).innerHTML=e}e.FontFace&&e.FontFace.prototype.hasOwnProperty("display")?(t[r]&&f(t[r]),fetch(o).then(function(e){return e.text()}).then(function(e){return e.replace(/@font-face {/g,"@font-face{font-display:swap;")}).then(function(e){return t[r]=e}).then(f).catch(a)):a()}(window,document,localStorage);
</script>
<!-- End of code snippet for Google Fonts -->
```

It gets cut off at hyphen.

**Comment by iamakulov** [comment]
Oh right! It’s an issue with the regex here:

https://github.com/iamakulov/googlefonts-font-display-helper/blob/d53ecb27a9483cfae9193a2a2ce876f2c09d91ed/src/snippet-generator/index.hbs#L354

The regex lacks a hyphen because I missed that there’s a font subset with a hyphen (`chinese-traditional`).

Want to make a PR?

**Comment by joshuaavalon** [comment]
@iamakulov Is there a point to test user input instead of just use what ever they input?

**Comment by iamakulov** [comment]
​​My idea behind this was to make the tool easier to use. When you select a font in Google Fonts, they emit not just the stylesheet url, but the whole embed code:

![](https://i.imgur.com/8mHpgU2.jpg)

And I wanted to allow people to just copy that code and drop it into the input.

Not sure how many people have actually used that, but I’d say let’s keep it for now.

**Comment by iamakulov** [comment]
Hey @joshuaavalon! Would you like to proceed with the PR, or should I make the change? I’m fine with either option, asking just to avoid stealing that out of your hands :)

**Comment by joshuaavalon** [comment]
@iamakulov You can do it if you want.
