### ISSUE TITLE
FOUT: bug or feature?

### ISSUE THREAD

**Issue by halafi** [iamakulov/googlefonts-font-display-helper#14]
Tested out the snippet generated by the tool to improve google fonts loading, is a brief FOUT (flash of unstyled text) to be expected or an issue?

**Comment by iamakulov** [comment]
Yeah, that’s expected for the first load – that’s how [`font-display: swap`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) behaves (which is used under the hood). Basically, we trade FOIT for FOUT, allowing the visitor to see the text earlier, but showing it unstyled for a brief amount of time.

It’s not something that should happen for repeated loads though (if caching is enabled). If that’s what happens, please let me know!

(Closing the issue, but feel free to ask any other questions.)
