### ISSUE TITLE
Select charsets 

### ISSUE THREAD

**Issue by octoxalis** [iamakulov/googlefonts-font-display-helper#15]
It's a very useful tool, however, I'd like to be able to select the charsets I load, e.g. select Latin and Latin extended only without Cyrillic, etc.
Is there a way I can I tweak the script?

**Comment by iamakulov** [comment]
Hey @octoxalis! Generally, that’s something that you do in the Google Fonts UI:

![image](https://user-images.githubusercontent.com/2953267/53741965-99f66380-3ea8-11e9-8b7b-1e4358152c06.png)

Google Fonts would give you the stylesheet URL that’s tuned to include only specific charsets. Then, you just paste that URL into the tool and grab the resulting code.

Hope that helps.

(I’ll close the issue, but feel free to add any other questions or comments.)
