### ISSUE TITLE
Conflict with mutiple instances

### ISSUE THREAD

**Issue by unsafecode** [iamakulov/googlefonts-font-display-helper#18]
Whenever using the script more than once (for more fonts), only the latest one will be applied. 

At least, please add a note about changing the ID of the generated `<link>`

**Comment by iamakulov** [comment]
Oh right, that’s a great point. Sorry you’ve experienced this!

Want to make a PR? I think we can solve it on our side by generating a random ID and inserting it the same way we insert `%FONT_STYLESHEET%` and `%FONT_DISPLAY%`:

https://github.com/iamakulov/googlefonts-font-display-helper/blob/a6453598d32203bce506611e40d28ab4be849089/src/script.js#L4-L7

If we go with this approach, we’ll need to generate an ID in `src/snippet-generator` and append it to the unique ID in this line:

https://github.com/iamakulov/googlefonts-font-display-helper/blob/a6453598d32203bce506611e40d28ab4be849089/src/script.js#L11

**Comment by unsafecode** [comment]
@iamakulov I'd say fine for the random ID :)

**Comment by iamakulov** [comment]
@unsafecode Sure! Want to make a PR? Fine if not; I’ll do it myself then.
