### ISSUE TITLE
Option to choose between swap and fallback?

### ISSUE THREAD

**Issue by kurtextrem** [iamakulov/googlefonts-font-display-helper#23]
While I had always preferred `swap`, it might be that `fallback` is better sometimes/often? At least jsconf started using it: https://2019.jsconf.eu/news/how-we-built-the-fastest-conference-website-in-the-world/#font-display, sadly no details on why.

Anyway, I [quote](https://developers.google.com/web/updates/2016/02/font-display#differences_in_font_rendering_today):
> Logo text is a good candidate for `swap` since displaying a company’s name using a reasonable fallback will get the message across but you’d eventually use the official typeface.

> `fallback` is a good candidate for things like body text where you’d like the user to start reading as soon as possible and don’t want to disturb their experience by shifting text around as a new font loads in.

Maybe something like a toggle for:
- Logo Text
- Body Text

**Comment by iamakulov** [comment]
Closing, as the project is deprecated now (#26).
