### ISSUE TITLE
Time to deprecate the tool

### ISSUE THREAD

**Issue by kaknut** [iamakulov/googlefonts-font-display-helper#25]
Now Google fonts by default supports font-display so adding this code will unnecessarily increase the size of web page and also add complications for non techies.

**Comment by Leland** [comment]
For reference: https://github.com/google/fonts/issues/358#issuecomment-492324042

**Comment by iamakulov** [comment]
Thanks for the heads-up, folks! I definitely think it’s time to deprecate this, just didn’t have time lately.

**Comment by iamakulov** [comment]
Just added the deprecation message. Thanks!

**Comment by Mini-ghost** [comment]
I have a question. Although this tool has been Deprecated, can I still use preconnect in link element to improve the TCP/IP connection process ?

like this

```html
<link rel="dns-prefetch" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous">
<link rel="preload" href="//fonts.googleapis.com/cssfamily=Quicksand:300,400,500,700&amp;display=swap" as="style" crossorigin="anonymous">
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700&amp;display=swap">
```

**Comment by iamakulov** [comment]
Totally!

Note that `preconnect` includes `dns-prefetch`, so you only need the latter in older browsers (see the yellow note in of https://3perf.com/blog/link-rels/#dns-prefetch).

And you likely won't need `<link rel="preload">`. I'm not sure whether it would actually help: the stylesheet is right there in the HTML, so the browser starts loading the stylesheet tag quickly even without `preload`. And it could bring issues: `preload` has been overly aggressive in Chromium; so with `preload`, the Google Fonts stylesheet might get get scheduled earlier and steal bandwidth from more important resources. (I'd suggest testing with and without `preload` and comparing results.)

**Comment by kaknut** [comment]
Dns preconnect is recommended.
