### ISSUE TITLE
Fetch to prevent warning in console - is it the right way?

### ISSUE THREAD

**Issue by kurtextrem** [iamakulov/googlefonts-font-display-helper#7]
https://github.com/iamakulov/googlefonts-font-display-helper/blob/master/src/script.js#L37

I would rather add a 'warning' to the readme, that the warning can be ignored. Initiating a fetch just for the pleasure of developers sounds a bit counter-intuitive for performance.

**Comment by iamakulov** [comment]
My idea for doing `fetch()` is that `<link rel="preload">` already initiates the request, and `fetch()` merely hides the warning. It’s less than optimal, but that’s something we can’t change AFAIK (at least, I don’t see how).

Anyway, I think, after #10, the `fetch()` won’t be empty anymore.
