### ISSUE TITLE
Uglifyjs converts (function(){})() to !function(){}

### ISSUE THREAD

**Issue by kurtextrem** [iamakulov/googlefonts-font-display-helper#9]
...which is unoptimized in older browsers (https://github.com/nolanlawson/optimize-js). Not sure if it's worth trading 2 characters with possibly performance losses in older browsers.

UglifyJS needs those options to stay with (function(){}):
`compress: {
	negate_iife: false,
},
output: {
	wrap_iife: true,
},`

**Comment by iamakulov** [comment]
I’d agree with https://github.com/mishoo/UglifyJS2/issues/1307#issuecomment-250635373 that it’s something that should be handled in browser engines.

Also, might this be already fixed in V8? The `optimize-js` repo says it’s not maintained.

**Comment by iamakulov** [comment]
> Not sure if it's worth trading 2 characters with possibly performance losses in older browsers

Whoops, missed the point that you were talking about older browsers.
Anyway, JS is faster than network, and having two fewer bytes to transfer might be better in the end than being 10-20% faster in older Chromes and Firefoxes.
